swagger: "2.0"
info:
  description: "This is the API specification of SFSBroker.  This includes the details"
  version: "1.0.0"
  title: "REST API specification for SFSBroker Integration"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.swagger.io"
basePath: "/v2"

schemes:
- "https"
- "http"
paths:
  /resourceRequest:
    post:
      tags:
      - "ResourceRequest"
      summary: "Consumer initiates the resource request"
      description: ""
      operationId: "resourceRequest"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data elements of the individual resources and their quantities"
        required: true
        schema:
          $ref: "#/definitions/ResourceRequest"
      responses:
        "405":
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /updateMNOs:
    post:
      tags:
      - "ResourceRequest"
      summary: "Consumer initiates the resource request"
      description: ""
      operationId: "updateResourceAvaialability"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data elements of the individual resources and their quantities"
        required: true
        schema:
          $ref: "#/definitions/ResourceRequest"
      responses:
        "405":
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
     
 
 
   
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://inspire5G.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "Adds the "
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
 
  ResourceRequest:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
     
      tenantIdentifier:
        type: "string"
        example: "e86dfa01c678a31185338acca50535f0"
      resourceQuantity:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
     
     
      demandQuantity:
        type: "string"
        description: "Unit price quantities"
        enum:
        - "1"
        - "2"
        - "4"
    xml:
      name: "ResourceRequest"
     
  ResourceUpdateFromMNO:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
 
      mnoIdentifier:
        type: "string"
        example: "e86dfa01c678a31185338acca50535f0"
      resourceQuantityAvailable:
        type: "array"
        xml:
          name: ""
          wrapped: true
        items:
          type: "string"
     
     
      availableQuantity:
        type: "string"
        description: "Available quantities"
        enum:
        - "1"
        - "2"
        - "3"
        - "4"
         
    xml:
      name: "ResourceRequest1"
 
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
